[build]
    base = "gatsby"
    publish = "public"
    command = "yarn run build"

[context.production.environment]
    HUGO_VERSION = "0.30"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.30"
