[build]
  base    = "site"
  publish = "_hugo"
  command = "npm install && npm run build"

[context.production.environment]
    HUGO_VERSION = "0.30"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.30"
